name: Django CI/CD
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
    - name: Run Tests
      run: python manage.py test -v 2
    - name: linting
      uses: programmingwithalex/pylinter@main
      with:
        flake8-flags: '--count --show-source --statistics --exclude=Taskify/settings.py'
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: true
        skip-flake8: false
    - name: Django Security Check
      uses: victoriadrake/django-security-check@v1.1.0
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Django aws eb deployment
  #     uses: joel-hanson/django-aws-eb-deploy@V1.1
  #     with:
  #       python_version: ${{ matrix.python_version }}
  #       aws_access_key_id: ${{ secrets.aws_access_key_id }}
  #       aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
  #       deploy: true
  #       unit_testing: true
  #       min_coverage: 10
