name: Django CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
    - name: Run Tests
      run: python manage.py test -v 2
    - name: linting
      uses: programmingwithalex/pylinter@main
      with:
        python-root: '.'
        flake8-flags: '--count --show-source --statistics --exclude=Taskify/settings.py'
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: true
        skip-flake8: false
    - name: Django Security Check
      uses: victoriadrake/django-security-check@v1.1.0
