name: Django CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Taskify/requirements.txt
    - name: Run Tests
      run: |
        pwd
        ls
        python manage.py test
    - name: linting
      uses: programmingwithalex/pylinter@main
      with:
        python-root: '.'
        flake8-flags: '--count --show-source --statistics'
        mypy-flags: '--ignore-missing-imports'
        fail-on-isort: true
        mypy-ignore-dirs-files: 'Taskify/settings.py'
        skip-flake8: false
    - name: Django Security Check
      uses: victoriadrake/django-security-check@v1.1.0
    - name: Python Django Coverage GitHub Action
      uses: dc740/django-coveragepy-github-action@0.9
