name: Linting

needs: install-deps

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
        with:
          path: .

      - name: linting
        uses: programmingwithalex/pylinter@main
